services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: finance_manager
      POSTGRES_USER: chukwuebuka
      POSTGRES_PASSWORD: Icui4cu2
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - IN_DOCKER=true # Explicitly set to detect Docker environment
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
