services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/mvp-fintech
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEBUG: ${DEBUG:-'False'}  # Default to 'False' if not set
      DB_NAME: finance_manager
      DB_USER: chukwuebuka
      DB_PASSWORD: Icui4cu2
      DB_HOST: db
      DB_PORT: 5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: finance_manager
      POSTGRES_USER: chukwuebuka
      POSTGRES_PASSWORD: Icui4cu2
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chukwuebuka -d finance_manager"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine

volumes:
  pgdata:
